### ISSUE TITLE
Misformatted error message leaves out details.

### ISSUE THREAD

**Issue by jshook** [virtualdataset/metagen-java#17]
The error below was actually for 'RandomToByteBuffer(1048576) ; ToString()'
~~~
17:53:03.464 [batch:001] ERROR i.v.c.FunctionalDataMappingLibrary - Error while trying to instantiate:[io.virtdata.functional.RandomToByteBuffer, 1048576,  ; ToString(]
17:53:03.465 [scenarios:001] INFO  c.datastax.ebdrivers.cql.CqlActivity - Shutting down session and cluster.
Exception in thread "batch:001" java.lang.NumberFormatException: For input string: " ; ToString("
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:578)
    at java.lang.Long.valueOf(Long.java:803)
~~~

**Comment by jshook** [comment]
Added test for this, not enough data to reproduce actual issue.
